### PR TITLE
Mask now accepts passed styles.

### PR DESCRIPTION
**Pull request by andrejborstnik**

### CODE REVIEW

**Comment by maicki** [comment]
Hey @andrejborstnik thanks for the PR. We deliberately don't expose the style prop within `react-native-mask`. What are you trying to archive?

**Comment by andrejborstnik** [comment]
Mostly shadows and borders around the mask. But I would like shadows only on a part of the border. Having no control over mask styles makes it tricky to implement. 

I understand accepting all styles could break the desired mask effect and you might not want them. Do you use shadows/borders and do you have a workaround for them? Have you considered passing styles, that do not break mask behaviour?

**Comment by maicki** [comment]
I would suggest you hosting the `Mask` component in a `View` component and apply the style to the `View`:

```
<View style={...}>
  <Mask ...>
  ...
  </Mask>
</View>
```

`Mask` should really just be there to apply a mask to it's children and the purpose is not to also apply some styling.

**Comment by andrejborstnik** [comment]
True. But if I want to apply a border/shadow with the shape of my masked content, I would need to reproduce the mask it in the View component, which defeats the purpose of having a mask component.

No worries if my weird usecase is not consistent with your usecase :D. And thank you for your replies.

**Pull request closed without merging**
